// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnovfuuypnipwspkcvvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRub3ZmdXV5cG5pcHdzcGtjdnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjExMjUsImV4cCI6MjA1OTA5NzEyNX0.krmx_HGxpmZAvcKEXXjuV1yFE8h87OnwyGiIkDllUoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);